services:
  mongodb:
    image: mongo:7
    container_name: gestion_stage_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: gestion_stage_backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/gestion_stages
      JWT_SECRET: gestion_stage_secret_key
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: gestion_stage_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo_data: